//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tarunov_Danila_Peresdacha
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abonenti_1
    {
        public int ID { get; set; }
        public string Nomer_abonenta { get; set; }
        public string FIO { get; set; }
        public string Pol { get; set; }
        public string Data_rojgenia { get; set; }
        public string Nomer_telefona { get; set; }
        public string Email { get; set; }
        public string Adres_propiski { get; set; }
        public string Adres_progjivania { get; set; }
        public string Kem_vidan { get; set; }
        public string Nomer_dogovora { get; set; }
        public string Data_zakluchenia { get; set; }
        public string Tip_dogovora { get; set; }
        public string Prichina_rastorgjenia { get; set; }
        public string Licevoi_nomer { get; set; }
        public string Uslugi { get; set; }
        public string Data_rastorjgenia { get; set; }
        public string Nomer_oborydovania { get; set; }
    }
}
