//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tarunov_Danila_Peresdacha
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.ModelConfiguration.Configuration;

    public partial class Tarunov_peresdacha11Entities2 : DbContext
    {
        public static Tarunov_peresdacha11Entities2 context;
        public static Tarunov_peresdacha11Entities2 Getcontext()
        {
            if (context == null)
            {
                context = new Tarunov_peresdacha11Entities2();
            }
            return context;
        }
        public Tarunov_peresdacha11Entities2()
            : base("name=Tarunov_peresdacha11Entities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Abonenti_1> Abonenti_1 { get; set; }
        public virtual DbSet<Avtorizacia> Avtorizacia { get; set; }
        public virtual DbSet<Info_sotrudniki> Info_sotrudniki { get; set; }
        public virtual DbSet<Oborudovanie> Oborudovanie { get; set; }
        public virtual DbSet<Sotrudniki> Sotrudniki { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
