//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tarunov_Danila_Peresdacha
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oborudovanie
    {
        public int ID { get; set; }
        public string Nomer_obiekta { get; set; }
        public string Nazvanie { get; set; }
    }
}
